export const provideAppContext = (provide, context) => {
  provide('messages', context.messages)
  provide('isTyping', context.isTyping)
  provide('streamingContent', context.streamingContent)
  provide('isStreaming', context.isStreaming)
  provide('streamingModel', context.streamingModel)
  provide('models', context.models)
  provide('currentModel', context.currentModel)
  provide('skills', context.skills)
  provide('apiConfig', context.apiConfig)
  provide('isLightMode', context.isLightMode)
  provide('permissionDialog', context.permissionDialog)
  provide('conversations', context.conversations)
  provide('activeConversationId', context.activeConversationId)
  provide('apiBase', context.apiBase)
  provide('routingConfig', context.routingConfig)
  provide('lastRouteInfo', context.lastRouteInfo)
  provide('liveUsage', context.liveUsage)
  provide('streamMeta', context.streamMeta)
  provide('voiceRuntime', context.voiceRuntime)
  provide('apiClient', context.api)
  provide('notify', context.notify)
  provide('exportConversation', context.exportConversation)
  provide('switchModel', context.switchModel)
  provide('clearHistoryFn', context.clearHistory)
  provide('createConversationFn', context.createConversation)
  provide('appActions', context.appActions)
}
